[PARSER]
    Name        json
    Format      json
    Time_Key    timestamp
    Time_Format %Y-%m-%dT%H:%M:%S

[PARSER]
    Name        nginx
    Format      regex
    Regex       ^(?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+) (?<path>[^"]*) (?<protocol>[^"]*)" (?<code>\d+) (?<size>\d+) "(?<referer>[^"]*)" "(?<agent>[^"]*)"$
    Time_Key    time
    Time_Format %d/%b/%Y:%H:%M:%S %z
