"""add_ticket_id_to_ticket

Revision ID: 4ba19ae9e84f
Revises: ad11761e2338
Create Date: 2026-05-09 16:30:34.900632
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ba19ae9e84f'
down_revision: Union[str, None] = 'ad11761e2338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_smart_workflow_kv_type_updated', table_name='smart_workflow_kv')
    op.drop_index('ix_smart_workflow_kv_type_workflow_created', table_name='smart_workflow_kv')
    op.drop_index('ix_smart_workflow_kv_type_workflow_user_unread_created', table_name='smart_workflow_kv')
    op.drop_table('smart_workflow_kv')
    op.alter_column('tickets', 'ticket_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               nullable=False)
    op.create_index('ix_tickets_company_id', 'tickets', ['company_id'], unique=False)
    op.create_index('ix_tickets_ticket_id', 'tickets', ['ticket_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index('ix_tickets_ticket_id', table_name='tickets')
    op.drop_index('ix_tickets_company_id', table_name='tickets')
    op.alter_column('tickets', 'ticket_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.create_table('smart_workflow_kv',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('is_unread', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payload_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='smart_workflow_kv_pkey'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_smart_workflow_kv_type_id')
    )
    op.create_index('ix_smart_workflow_kv_type_workflow_user_unread_created', 'smart_workflow_kv', ['entity_type', 'workflow_id', 'user_id', 'is_unread', 'payload_created_at'], unique=False)
    op.create_index('ix_smart_workflow_kv_type_workflow_created', 'smart_workflow_kv', ['entity_type', 'workflow_id', 'payload_created_at'], unique=False)
    op.create_index('ix_smart_workflow_kv_type_updated', 'smart_workflow_kv', ['entity_type', 'updated_at'], unique=False)
    # ### end Alembic commands ###
