"""Stage-6 spatiotemporal forecasting module."""

from .analysis_tools import (
    acf,
    adf_proxy_test,
    cross_correlation,
    detect_spatiotemporal_anomalies,
    detect_temporal_anomalies,
    fft_spectrum,
    kpss_proxy_test,
    pacf,
    seasonal_decompose,
)
from .attention import (
    AttentionOutput,
    attention_pooling,
    multi_head_attention,
    spatial_multi_head_attention,
    spatiotemporal_multi_head_attention,
    temporal_multi_head_attention,
)
from .data import (
    SlidingWindowDataLoader,
    SpatialNormalizer,
    SpatioTemporalDataAugmentation,
    SpatioTemporalFeatureEngineer,
    SpatioTemporalGraphBuilder,
    SpatioTemporalSample,
    SyntheticSpatioTemporalDataset,
    TemporalNormalizer,
)
from .evaluation import (
    SpatioTemporalMetrics,
    ablation_study,
    benchmark_comparison,
    evaluate_spatial_dimension,
    evaluate_spatiotemporal_metrics,
    evaluate_time_dimension,
    generate_report,
)
from .graph import SpatioTemporalGraph, build_knn_graph, update_dynamic_graph
from .integration import IntegratedSpatioTemporalResult, SpatioTemporalSystemIntegrator
from .losses import (
    combined_spatiotemporal_loss,
    gaussian_nll,
    mae_loss,
    mse_loss,
    quantile_loss,
    spatial_consistency_loss,
    temporal_consistency_loss,
)
from .models import (
    ConvLSTMModel,
    GCNLSTMModel,
    SpatioTemporalOutput,
    SpatioTemporalTransformer,
    STGCNModel,
)
from .online import (
    OnlineModelUpdater,
    OnlineSpatioTemporalPredictor,
    OnlineUpdateResult,
)
from .optimization import LongSequenceOutput, SpatioTemporalPerformanceOptimizer
from .position_encoding import (
    normalize_spatial_positions,
    normalize_temporal_positions,
    relative_spatial_position_encoding,
    relative_temporal_position_encoding,
    sinusoidal_spatial_position_encoding,
    sinusoidal_temporal_position_encoding,
)
from .st_fusion import STModelFusion
from .st_gnn import STGNNPredictor, STGNNResult
from .st_transformer import STTransformerPredictor, STTransformerResult
from .st_uncertainty import STUncertaintyQuantifier, STUncertaintyResult
from .training import (
    SpatioTemporalHyperparameterOptimizer,
    SpatioTemporalModelManager,
    SpatioTemporalTrainingConfig,
    SpatioTemporalTrainingMonitor,
    cosine_with_warmup,
    train_spatiotemporal_model,
)

__all__ = [
    "SpatioTemporalTransformer",
    "GCNLSTMModel",
    "ConvLSTMModel",
    "STGCNModel",
    "SpatioTemporalOutput",
    "AttentionOutput",
    "multi_head_attention",
    "spatial_multi_head_attention",
    "temporal_multi_head_attention",
    "spatiotemporal_multi_head_attention",
    "attention_pooling",
    "SpatioTemporalGraph",
    "build_knn_graph",
    "update_dynamic_graph",
    "sinusoidal_spatial_position_encoding",
    "sinusoidal_temporal_position_encoding",
    "relative_spatial_position_encoding",
    "relative_temporal_position_encoding",
    "normalize_spatial_positions",
    "normalize_temporal_positions",
    "mse_loss",
    "mae_loss",
    "quantile_loss",
    "temporal_consistency_loss",
    "spatial_consistency_loss",
    "gaussian_nll",
    "combined_spatiotemporal_loss",
    "SpatioTemporalMetrics",
    "evaluate_spatiotemporal_metrics",
    "evaluate_time_dimension",
    "evaluate_spatial_dimension",
    "benchmark_comparison",
    "ablation_study",
    "generate_report",
    "SpatioTemporalSample",
    "SyntheticSpatioTemporalDataset",
    "SpatioTemporalDataAugmentation",
    "SpatioTemporalFeatureEngineer",
    "TemporalNormalizer",
    "SpatialNormalizer",
    "SpatioTemporalGraphBuilder",
    "SlidingWindowDataLoader",
    "SpatioTemporalTrainingConfig",
    "SpatioTemporalTrainingMonitor",
    "SpatioTemporalHyperparameterOptimizer",
    "SpatioTemporalModelManager",
    "cosine_with_warmup",
    "train_spatiotemporal_model",
    "OnlineUpdateResult",
    "OnlineSpatioTemporalPredictor",
    "OnlineModelUpdater",
    "LongSequenceOutput",
    "SpatioTemporalPerformanceOptimizer",
    "IntegratedSpatioTemporalResult",
    "SpatioTemporalSystemIntegrator",
    "seasonal_decompose",
    "adf_proxy_test",
    "kpss_proxy_test",
    "acf",
    "pacf",
    "cross_correlation",
    "fft_spectrum",
    "detect_temporal_anomalies",
    "detect_spatiotemporal_anomalies",
    "STGNNPredictor",
    "STGNNResult",
    "STUncertaintyQuantifier",
    "STUncertaintyResult",
    "STModelFusion",
    "STTransformerPredictor",
    "STTransformerResult",
]
